package com.totvslabs.mdm.restclient.vo;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Staging Schema VO
 * 
 * @author TOTVS Labs
 *
 */
public class StagingSchemaVO extends GenericVO {
	private String mdmStagingDataSourceId;
	private String mdmStagingType;
	private MappingVO mdmStagingMapping;
	private CrosswalkTemplateVO mdmCrosswalkTemplate;
	boolean autoGenerated;

	/**
	 * @return the mdmStagingDataSourceId
	 */
	public String getmdmStagingDataSourceId() {
		return mdmStagingDataSourceId;
	}

	/**
	 * @param mdmStagingDataSourceId
	 *            the mdmStagingDataSourceId to set
	 */
	public void setmdmStagingDataSourceId(String mdmStagingDataSourceId) {
		this.mdmStagingDataSourceId = mdmStagingDataSourceId;
	}

	/**
	 * @return the mdmStagingType
	 */
	public String getmdmStagingType() {
		return mdmStagingType;
	}

	/**
	 * @param mdmStagingType
	 *            the mdmStagingType to set
	 */
	public void setmdmStagingType(String mdmStagingType) {
		this.mdmStagingType = mdmStagingType;
	}

	/**
	 * @return the mdmStagingMapping
	 */
	public MappingVO getmdmStagingMapping() {
		return mdmStagingMapping;
	}

	/**
	 * @param mdmStagingMapping
	 *            the mdmStagingMapping to set
	 */
	public void setmdmStagingMapping(MappingVO mdmStagingMapping) {
		this.mdmStagingMapping = mdmStagingMapping;
	}

	/**
	 * @return the mdmCrosswalkTemplate
	 */
	public CrosswalkTemplateVO getmdmCrosswalkTemplate() {
		return mdmCrosswalkTemplate;
	}

	/**
	 * @param mdmCrosswalkTemplate
	 *            the mdmCrosswalkTemplate to set
	 */
	public void setmdmCrosswalkTemplate(
			CrosswalkTemplateVO mdmCrosswalkTemplate) {
		this.mdmCrosswalkTemplate = mdmCrosswalkTemplate;
	}

	/**
	 * @return the autoGenerated
	 */
	public boolean isAutoGenerated() {
		return autoGenerated;
	}

	/**
	 * @param autoGenerated
	 *            the autoGenerated to set
	 */
	public void setAutoGenerated(boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}

}

class CrosswalkTemplateVO {
	private Map<String, List<String>> mdmCrossreference = new HashMap<>();

	public Map<String, List<String>> getMdmCrossreference() {
		return mdmCrossreference;
	}

	public void setMdmCrossreference(
			Map<String, List<String>> mdmCrossreference) {
		this.mdmCrossreference = mdmCrossreference;
	}
}
